application: congratboto
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /poll\.html
  script: page_handler.py

- url: /credentials
  script: admin/set_credentials.py
  login: admin
  secure: always

- url: /.*
  script: page_handler.py
